@server = http://localhost:4000
@createdUserId = {{createUser.response.body.$.id}}

### create a user
# @name createUser

POST {{server}}/users
Content-Type: application/json

{
  "nome": "João Silva",
  "email": "joao.silva@empresa.com",
  "usuario": "joaosilva",
  "senha": "123456"
}

### list users
GET {{server}}/users

### show a user
GET {{server}}/users/{{createdUserId}}

### update a user
PUT {{server}}/users/{{createdUserId}}
Content-Type: application/json

{
  "nome": "João Silva",
  "email": "joao.silva@empresa.com",
  "usuario": "joaosilva",
  "senha": "novaSenha123"
}

### delete a user
DELETE {{server}}/users/{{createdUserId}}
